### ISSUE TITLE
Error compiling for board Arduino

### ISSUE THREAD

**Issue by Roberto6969** [jbanaszczyk/pms5003#1]
Great work! Would you check the following error (in Arduino IDE version 1.8.1):
\Documents\Arduino\libraries\pms5003-master\src\pms.cpp: In member function 'bool Pms5003::begin()':

\Documents\Arduino\libraries\pms5003-master\src\pms.cpp:73:27: error: could not convert 'AltSoftSerial::begin(9600ul)' from 'void' to 'bool'

  if (!pmsSerial.begin(9600)) {

                           ^

C:\Users\Robert\Documents\Arduino\libraries\pms5003-master\src\pms.cpp:73:27: error: in argument to unary !

**Comment by jbanaszczyk** [comment]
Please use this fork
https://github.com/DrDiettrich/AltSoftSerial
It is much more stable

This week I will redesign statuses,  and I'll remove dependency on boost.tribool
