### ISSUE TITLE
PMS5003I and PMS7003I  I2C sensors

### ISSUE THREAD

**Issue by GrubiLabs** [jbanaszczyk/pms5003#10]
I'll need a bit of help to adapt/make this library working with
PMS5003I and PMS7003I, but I am mostly hardware guy and don't
really have expereince with write/modify libraries.
I wrote in the Arduino forum and understood it is not impossible
but will need some work to be done.
I do connect 5003I to Arduino Uno (via level adapter) and I2C
scanner successfully found 0x12 address which those sensors have.
How can advice me to go further?

**Comment by JAHSEHXKYLE** [comment]
bro where is the answer？？？？
