### ISSUE TITLE
Problem Including AltSoftSerial.h

### ISSUE THREAD

**Issue by Legend2015** [jbanaszczyk/pms5003#4]
Hello, I am trying to use this library for my PMS sensors and have run into a problem. I am using the modified AltSoftSerial Library as suggested. But when i try to compile i am getting this error. 

> Arduino: 1.6.5 (Windows 8.1), Board: "Arduino/Genuino Uno"
>
>Build options changed, rebuilding all
>
>In file included from C:\Program Files (x86)\Arduino\libraries\pms5003-master\src/pms.h:7:0,
 >                from PMS5003_1.ino:3:
>C:\Program Files (x86)\Arduino\libraries\pms5003-master\src/pmsConfig.h:37:27: fatal error: >AltSoftSerial.h: No such file or directory
 >#include <AltSoftSerial.h>
>                           ^
>compilation terminated.
>Error compiling.

  Could you please help me as to what might be going wrong?

Thank you so much

**Comment by jbanaszczyk** [comment]
AltSoftSerial is not installed.
Follow the link: https://www.arduino.cc/en/Guide/Libraries

**Comment by Legend2015** [comment]
Hi,

I can see AltSoftSerial installed when i go Sketch -> Include Library under the Contributed Libraries section. Also, when i manually add "#include <AltSoftSerial.h>" in the Simple01.ino it gives mea different set of errors like "'wakeupTime' is not a member of 'Pms5003'". The same error comes up after i manually changed "#include <AltSoftSerial.h>" to "#include <../../AltSoftSerial/AltSoftSerial.h> in pmsConfig.h. That tells me it is able to find the AltSoftSerial.h this way. The full text of the error is as follows:

`Arduino: 1.6.5 (Mac OS X), Board: "Arduino/Genuino Uno"

In file included from /Applications/Arduino.app/Contents/Java/libraries/pms5003/src/pms.h:6:0,
                 from Simple01.ino:3:
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:19:1: error: 'constexpr' does not name a type
 constexpr inline bool unknown(tribool arg, unknown_t dummy = unknown_t());
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:19:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:25:2: error: 'constexpr' does not name a type
  constexpr tribool() : value(unknown_v) {}
  ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:25:2: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:26:2: error: 'constexpr' does not name a type
  constexpr tribool(bool v) : value(v ? true_v : false_v) {};
  ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:26:2: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:27:2: error: 'constexpr' does not name a type
  constexpr tribool(unknown_keyword_t) : value(unknown_v) {}
  ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:27:2: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:28:2: error: 'constexpr' does not name a type
  constexpr inline operator bool() const {
  ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:28:2: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:32:2: error: 'constexpr' does not name a type
  constexpr inline tribool operator!() const {
  ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:32:2: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:41:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator&&(tribool lhs, tribool rhs) {
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:41:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:48:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator&&(tribool lhs, bool rhs) { return rhs ? lhs : tribool(false); }
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:48:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:49:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator&&(bool lhs, tribool rhs) { return lhs ? rhs : tribool(false); }
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:49:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:50:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator&&(unknown_keyword_t, tribool lhs) { return !lhs ? tribool(false) : tribool(unknown); }
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:50:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:51:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator&&(tribool lhs, unknown_keyword_t) { return !lhs ? tribool(false) : tribool(unknown); }
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:51:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:53:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator||(tribool lhs, tribool rhs) {
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:53:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:60:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator||(tribool lhs, bool rhs) { return rhs ? tribool(true) : lhs; }
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:60:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:61:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator||(bool lhs, tribool rhs) { return lhs ? tribool(true) : rhs; }
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:61:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:62:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator||(unknown_keyword_t, tribool lhs) { return lhs ? tribool(true) : tribool(unknown); }
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:62:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:63:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator||(tribool lhs, unknown_keyword_t) { return lhs ? tribool(true) : tribool(unknown); }
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:63:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:65:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator==(tribool lhs, tribool rhs) {
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:65:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:71:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator==(tribool lhs, bool rhs) { return lhs == tribool(rhs); }
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:71:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:72:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator==(bool lhs, tribool rhs) { return tribool(lhs) == rhs; }
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:72:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:73:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator==(unknown_keyword_t, tribool lhs) { return tribool(unknown) == lhs; }
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:73:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:74:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator==(tribool lhs, unknown_keyword_t) { return tribool(unknown) == lhs; }
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:74:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:76:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator!=(tribool lhs, tribool rhs) {
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:76:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:82:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator!=(tribool lhs, bool rhs) { return lhs != tribool(rhs); }
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:82:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:83:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator!=(bool lhs, tribool rhs) { return tribool(lhs) != rhs; }
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:83:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:84:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator!=(unknown_keyword_t, tribool lhs) { return tribool(unknown) != lhs; }
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:84:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:85:1: error: 'constexpr' does not name a type
 constexpr inline tribool operator!=(tribool lhs, unknown_keyword_t) { return lhs != tribool(unknown); }
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:85:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:87:1: error: 'constexpr' does not name a type
 constexpr inline bool unknown(tribool arg, unknown_t dummy) { return false; };
 ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/tribool.h:87:1: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
In file included from Simple01.ino:3:0:
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/pms.h:26:24: error: 'timeout' is not a type
  static const decltype(timeout) timeoutPassive = 68;  // Transfer time of 1start + 32data + 1stop using 9600bps is 33 usec. timeoutPassive could be at least 34, Value of 68 is an arbitrary doubled
                        ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/pms.h:26:31: error: ISO C++ forbids declaration of 'decltype' with no type [-fpermissive]
  static const decltype(timeout) timeoutPassive = 68;  // Transfer time of 1start + 32data + 1stop using 9600bps is 33 usec. timeoutPassive could be at least 34, Value of 68 is an arbitrary doubled
                               ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/pms.h:26:31: error: expected ';' at end of member declaration
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/pms.h:26:33: error: 'timeoutPassive' does not name a type
  static const decltype(timeout) timeoutPassive = 68;  // Transfer time of 1start + 32data + 1stop using 9600bps is 33 usec. timeoutPassive could be at least 34, Value of 68 is an arbitrary doubled
                                 ^
In file included from Simple01.ino:3:0:
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/pms.h:27:20: error: 'ackTimeout' does not name a type
  static const auto ackTimeout = 30U;                  // Time to complete response after write command
                    ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/pms.h:76:40: error: ISO C++ forbids declaration of 'decltype' with no type [-fpermissive]
  void setTimeout(const decltype(timeout) timeout);
                                        ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/pms.h:76:32: error: expected ',' or '...' before '(' token
  void setTimeout(const decltype(timeout) timeout);
                                ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/pms.h:77:11: error: 'timeout' is not a type
  decltype(timeout) getTimeout(void) const;
           ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/pms.h:77:18: error: ISO C++ forbids declaration of 'decltype' with no type [-fpermissive]
  decltype(timeout) getTimeout(void) const;
                  ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/pms.h:77:18: error: expected ';' at end of member declaration
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/pms.h:77:2: error: 'int Pms5003::decltype(int)' cannot be overloaded
  decltype(timeout) getTimeout(void) const;
  ^
In file included from Simple01.ino:3:0:
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/pms.h:26:15: error: with 'static const int Pms5003::decltype(int)'
  static const decltype(timeout) timeoutPassive = 68;  // Transfer time of 1start + 32data + 1stop using 9600bps is 33 usec. timeoutPassive could be at least 34, Value of 68 is an arbitrary doubled
               ^
In file included from Simple01.ino:3:0:
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/pms.h:77:37: error: ISO C++ forbids declaration of 'getTimeout' with no type [-fpermissive]
  decltype(timeout) getTimeout(void) const;
                                     ^
/Applications/Arduino.app/Contents/Java/libraries/pms5003/src/pms.h:79:20: error: 'wakeupTime' does not name a type
  static const auto wakeupTime = 2500U;    // Experimentally, time to get ready after reset/wakeup
                    ^
Simple01.ino: In function 'void setup()':
Simple01:15: error: 'wakeupTime' is not a member of 'Pms5003'
Simple01.ino: At global scope:
Simple01:21: error: 'lastRead' does not name a type
Simple01.ino: In function 'void loop()':
Simple01:25: error: 'n' does not name a type
Simple01:26: error: 'n' was not declared in this scope
Simple01:28: error: 'data' was not declared in this scope
Simple01:34: error: 'newRead' does not name a type
Simple01:36: error: 'newRead' was not declared in this scope
Simple01:36: error: 'lastRead' was not declared in this scope
'wakeupTime' is not a member of 'Pms5003'

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
`
I tried it in both my Windows 10 laptop and MacBook Pro, with same errors. :(

**Comment by jbanaszczyk** [comment]
You use very old Arduino, without support for C++11. Please upgrade.
