### ISSUE TITLE
compile: use of enum error

### ISSUE THREAD

**Issue by riverscn** [jbanaszczyk/pms5003#6]
lib/pms5003/src/pms.h:44:7: error: use of enum 'PmsCmd' without previous declaration
enum PmsCmd : __uint24 {
^
lib/pms5003/src/pms.h:44:16: error: '__uint24' was not declared in this scope
enum PmsCmd : __uint24 {
^

On PlatformIO ESP8266

**Comment by jbanaszczyk** [comment]
Which version of Arduino are you using?

**Comment by riverscn** [comment]
It's PlatformIO with updated packages.

**Comment by riverscn** [comment]
Tried also in Arduino 1.8.3 with ESP8266 board. Same error message.

**Comment by jbanaszczyk** [comment]
I'll fix it during the weekend. 
__uint24 is an Arduino-specific type
Temporary fix - just remove the word __uint24

**Comment by riverscn** [comment]
Thank you!
