### ISSUE TITLE
how to read out pmsx003::pmsIdx?

### ISSUE THREAD

**Issue by maddhin** [jbanaszczyk/pms5003#7]
Hi, this is probably a totally stupid beginner question, but I'm working with the basic sketch and want to publish the PM data with MQTT and want to add pmsIdx as part of the topic to get for each i the relevant topic such as /livingroom/PMS7003/PM1dot0 etc.
I tried (successfully) with dataNames but that is the description and not Idx...

 for (size_t i = Pmsx003::PM1dot0; i < n; ++i) { 
        Serial.print(data[i]);
        Serial.print("\t");
        Serial.print(Pmsx003::dataNames[i]);
        Serial.print(" [");
        Serial.print(Pmsx003::metrics[i]);
        Serial.println();
        String topic_send = topic_root;
        topic_send += Pmsx003::dataNames[i];
        Serial.print("Sending via ");
        Serial.println(topic_send); 
        client.publish(String(topic_send).c_str(), String(data[i]).c_str(),true);
        }

Thanks for any help!

**Comment by jbanaszczyk** [comment]
Sorry. Please clarify. Where is the problem?
